import { useState, type ReactNode } from 'react';
import { Link, useLocation } from 'wouter';
import {
  ArrowRight, Bell, BriefcaseBusiness, CalendarDays, Check, ChevronDown, CircleHelp,
  FileText, Heart, Home, LogOut, MapPin, Menu, Search, Settings2, SlidersHorizontal,
  Sparkles, Star, UserRound, Wrench, X, Zap, Droplets, Snowflake, Refrigerator,
  WashingMachine, Hammer, Paintbrush, Smartphone, Monitor, Laptop, Battery,
  Bike, Car, CircleDot, Camera, ShieldCheck,
} from 'lucide-react';
import type { ServiceCategory, Technician } from '@workspace/api-client-react';

export type Category = ServiceCategory;
export type MarketplaceTechnician = Technician;
export type Request = { id: string; service: string; technicianName: string; customerName: string; schedule: string; status: string; amount: number };

export const categoryGroups = ['Home Services', 'Repair Services', 'Vehicle Services'] as const;

export const fallbackCategories: Category[] = [
  ['electrician', 'Electrician', 'bolt', 'Electrical repair and installation', 'Home Services', 249],
  ['plumber', 'Plumber', 'droplet', 'Pipe leakage and plumbing services', 'Home Services', 199],
  ['ac-repair', 'AC Repair', 'snowflake', 'AC servicing and repair', 'Home Services', 399],
  ['refrigerator-repair', 'Refrigerator Repair', 'refrigerator', 'Cooling and fridge repairs', 'Home Services', 399],
  ['washing-machine-repair', 'Washing Machine Repair', 'washing-machine', 'Drum, drain and spin issues', 'Home Services', 349],
  ['ro-service', 'RO Service', 'droplets', 'Filter change and purifier care', 'Home Services', 299],
  ['carpenter', 'Carpenter', 'hammer', 'Furniture, shelves and woodwork', 'Home Services', 299],
  ['painter', 'Painter', 'paintbrush', 'Walls, touch-ups and finishes', 'Home Services', 499],
  ['cctv-technician', 'CCTV Technician', 'cctv', 'Camera setup and security checks', 'Home Services', 399],
  ['mobile-repair', 'Mobile Repair', 'smartphone', 'Screen, battery and software help', 'Repair Services', 199],
  ['computer-repair', 'Computer Repair', 'monitor', 'Desktop troubleshooting and upgrades', 'Repair Services', 299],
  ['laptop-repair', 'Laptop Repair', 'laptop', 'Laptop servicing and parts', 'Repair Services', 399],
  ['inverter-repair', 'Inverter Repair', 'battery', 'Backup power and battery care', 'Repair Services', 349],
  ['bike-mechanic', 'Bike Mechanic', 'bike', 'Pick-up, repair and tune-up', 'Vehicle Services', 299],
  ['car-mechanic', 'Car Mechanic', 'car', 'At-home checks and fixes', 'Vehicle Services', 499],
  ['battery-service', 'Battery Service', 'battery', 'Jumpstart and replacement', 'Vehicle Services', 249],
  ['tyre-repair', 'Tyre Repair', 'circle', 'Puncture repair and tyre changes', 'Vehicle Services', 149],
].map(([id, name, icon, description, group, startingPrice]) => ({
  id: id as string, name: name as string, icon: icon as string, description: description as string,
  slug: id as string, parentCategory: `${String(group).toLowerCase().replaceAll(' ', '-')}`,
  group: group as string, startingPrice: startingPrice as number, active: true,
}));

const tech = (id: string, name: string, specialty: string, serviceCategories: string[], rating: number, reviewCount: number, distance: string, location: string, avatar: string, availableToday: boolean, experience: number, shortDescription: string): MarketplaceTechnician & { experience: number; shortDescription: string } => ({
  id, name, specialty, serviceCategories, rating, reviewCount, distance, location, avatar,
  verified: true, availableToday, experience, shortDescription,
});

export const fallbackTechnicians = [
  tech('tech-ravi', 'Ravi Kumar', 'Electrician & security specialist', ['electrician', 'cctv-technician', 'inverter-repair'], 4.9, 128, '0.8 km', 'Indiranagar, Bengaluru', 'RK', true, 8, 'Fast, tidy electrical repairs with clear estimates.'),
  tech('tech-meena', 'Meena Sharma', 'Home appliance specialist', ['ac-repair', 'refrigerator-repair', 'washing-machine-repair'], 4.8, 86, '1.4 km', 'Koramangala, Bengaluru', 'MS', true, 7, 'Friendly appliance repairs and dependable follow-ups.'),
  tech('tech-imran', 'Imran Khan', 'Vehicle mechanic', ['bike-mechanic', 'car-mechanic', 'battery-service', 'tyre-repair'], 4.7, 204, '2.1 km', 'Domlur, Bengaluru', 'IK', false, 11, 'Reliable at-home vehicle checks and emergency help.'),
  tech('tech-raj', 'Raj Kumar', 'Electrician', ['electrician', 'cctv-technician'], 4.8, 74, '1.1 km', 'Ulsoor, Bengaluru', 'RK', true, 8, 'Electrical installation and repairs for homes and shops.'),
  tech('tech-pooja', 'Pooja Nair', 'Plumber', ['plumber', 'ro-service'], 4.6, 61, '1.7 km', 'Halasuru, Bengaluru', 'PN', true, 6, 'Leak detection, fittings and purifier maintenance.'),
  tech('tech-suresh', 'Suresh Babu', 'AC technician', ['ac-repair', 'refrigerator-repair'], 4.9, 142, '2.4 km', 'Ejipura, Bengaluru', 'SB', true, 12, 'Certified cooling expert for service and installation.'),
  tech('tech-divya', 'Divya Menon', 'Device repair expert', ['mobile-repair', 'laptop-repair', 'computer-repair'], 4.8, 97, '2.8 km', 'Vasanth Nagar, Bengaluru', 'DM', false, 9, 'Careful diagnostics for phones, laptops and computers.'),
  tech('tech-vikram', 'Vikram Singh', 'Carpenter & painter', ['carpenter', 'painter'], 4.5, 48, '3.2 km', 'Shivajinagar, Bengaluru', 'VS', true, 10, 'Thoughtful woodwork and neat home makeovers.'),
  tech('tech-anita', 'Anita Joseph', 'CCTV technician', ['cctv-technician', 'electrician'], 4.7, 53, '3.5 km', 'Richmond Town, Bengaluru', 'AJ', true, 5, 'Security camera setup and smart home wiring.'),
  tech('tech-karthik', 'Karthik Reddy', 'Bike mechanic', ['bike-mechanic', 'tyre-repair'], 4.6, 119, '1.9 km', 'Jayanagar, Bengaluru', 'KR', true, 7, 'Transparent bike servicing with doorstep pickup.'),
  tech('tech-neha', 'Neha Kapoor', 'Power backup specialist', ['inverter-repair', 'battery-service'], 4.8, 66, '4.1 km', 'BTM Layout, Bengaluru', 'NK', false, 9, 'Power backup, batteries and inverter troubleshooting.'),
  tech('tech-mohan', 'Mohan Das', 'RO and appliance technician', ['ro-service', 'washing-machine-repair'], 4.4, 39, '2.6 km', 'Sadashivanagar, Bengaluru', 'MD', true, 6, 'Practical appliance care with genuine spare parts.'),
];

export const fallbackRequests: Request[] = [
  { id: 'KK-2419', service: 'Ceiling fan repair', technicianName: 'Ravi Kumar', customerName: 'Aarav Mehta', schedule: 'Today, 4:30 PM', status: 'confirmed', amount: 349 },
  { id: 'KK-2388', service: 'Bike general service', technicianName: 'Imran Khan', customerName: 'Aarav Mehta', schedule: '18 Jun, 11:00 AM', status: 'completed', amount: 599 },
  { id: 'KK-2374', service: 'Kitchen tap replacement', technicianName: 'Pooja Nair', customerName: 'Aarav Mehta', schedule: '14 Jun, 2:00 PM', status: 'completed', amount: 280 },
];

const iconMap: Record<string, typeof Zap> = {
  bolt: Zap, droplet: Droplets, droplets: Droplets, snowflake: Snowflake, refrigerator: Refrigerator,
  'washing-machine': WashingMachine, hammer: Hammer, paintbrush: Paintbrush, cctv: Camera,
  smartphone: Smartphone, monitor: Monitor, laptop: Laptop, battery: Battery, bike: Bike,
  car: Car, circle: CircleDot,
};

export function getCategoryIcon(icon: string) {
  return iconMap[icon] || Wrench;
}

export function BrandMark({ dark = false }: { dark?: boolean }) {
  return <Link href="/" className="group inline-flex items-center gap-2.5" data-testid="link-brand"><span className="relative flex h-9 w-9 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-sm transition-transform group-hover:-rotate-6"><Wrench size={19} strokeWidth={2.5} /><span className="absolute -right-1 -top-1 h-2.5 w-2.5 rounded-full border-2 border-sidebar bg-accent" /></span><span className={`font-display text-xl font-bold tracking-tight ${dark ? 'text-sidebar-foreground' : 'text-foreground'}`}>Kaam<span className="text-primary">Khojo</span></span></Link>;
}

export function PublicHeader() {
  const [location] = useLocation();
  return <header className="fixed inset-x-0 top-0 z-40 border-b border-border/60 bg-background/90 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-7xl items-center justify-between px-5 lg:px-8"><BrandMark /><nav className="hidden items-center gap-8 md:flex"><a href="/#how-it-works" className="text-sm font-semibold text-muted-foreground hover:text-foreground">How it works</a><a href="/#services" className="text-sm font-semibold text-muted-foreground hover:text-foreground">Services</a><Link href="/technician-dashboard" className="text-sm font-semibold text-muted-foreground hover:text-foreground">For technicians</Link></nav><div className="flex items-center gap-2"><Link href="/login" className="hidden rounded-xl px-4 py-2.5 text-sm font-bold hover:bg-muted sm:inline-flex">Sign in</Link><Link href={location === '/' ? '/role-selection' : '/'} className="inline-flex items-center gap-2 rounded-xl bg-secondary px-4 py-2.5 text-sm font-bold text-secondary-foreground shadow-sm" data-testid="link-header-cta">Get started <ArrowRight size={15} /></Link></div></div></header>;
}

const navItems = [{ label: 'Overview', href: '/customer-dashboard', icon: Home }, { label: 'Find a technician', href: '/customer-dashboard#find', icon: Search }, { label: 'My requests', href: '/work-requests', icon: FileText }, { label: 'Saved technicians', href: '/customer-dashboard#saved', icon: Heart }];
const techNavItems = [{ label: 'Overview', href: '/technician-dashboard', icon: Home }, { label: 'Upcoming jobs', href: '/technician-dashboard#jobs', icon: CalendarDays }, { label: 'Earnings', href: '/technician-dashboard#earnings', icon: BriefcaseBusiness }, { label: 'Profile', href: '/profile', icon: UserRound }];

export function AppSidebar({ role = 'customer' }: { role?: 'customer' | 'technician' }) {
  const [location, setLocation] = useLocation();
  const [open, setOpen] = useState(false);
  const items = role === 'technician' ? techNavItems : navItems;
  const isActive = (href: string) => location === href || (href.includes('#') ? location === href.split('#')[0] : location.startsWith(href));
  const content = <aside className="flex h-full w-[260px] flex-col bg-sidebar px-4 py-5 text-sidebar-foreground"><div className="mb-9 flex items-center justify-between px-2"><BrandMark dark /><button onClick={() => setOpen(false)} className="rounded-lg p-2 text-sidebar-foreground/60 hover:bg-sidebar-accent md:hidden" aria-label="Close menu"><X size={18} /></button></div><div className="mb-6 rounded-2xl border border-sidebar-border bg-sidebar-accent/60 p-3.5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary font-display font-bold text-primary-foreground">{role === 'technician' ? 'RK' : 'AM'}</div><div className="min-w-0"><p className="truncate text-sm font-bold">{role === 'technician' ? 'Ravi Kumar' : 'Aarav Mehta'}</p><p className="truncate text-xs text-sidebar-foreground/55">{role === 'technician' ? 'Verified technician' : 'Customer account'}</p></div><ChevronDown size={15} className="ml-auto text-sidebar-foreground/50" /></div></div><p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-[.16em] text-sidebar-foreground/40">Workspace</p><nav className="space-y-1">{items.map(({ label, href, icon: Icon }) => <Link key={href} href={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${isActive(href) ? 'bg-primary text-primary-foreground shadow-sm' : 'text-sidebar-foreground/65 hover:bg-sidebar-accent hover:text-sidebar-foreground'}`}><Icon size={18} /><span>{label}</span>{label === 'My requests' && <span className="ml-auto rounded-full bg-sidebar-foreground/10 px-2 py-0.5 text-[10px]">2</span>}</Link>)}</nav><div className="mt-auto space-y-1"><Link href="/profile" onClick={() => setOpen(false)} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-sidebar-foreground/65 hover:bg-sidebar-accent hover:text-sidebar-foreground"><Settings2 size={18} /> Settings</Link><Link href="/" onClick={() => setOpen(false)} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-sidebar-foreground/65 hover:bg-sidebar-accent hover:text-sidebar-foreground"><LogOut size={18} /> Sign out</Link><div className="mt-5 border-t border-sidebar-border px-3 pt-5 text-xs text-sidebar-foreground/40">KaamKhojo <span className="mx-1">•</span> Made for your mohalla</div></div></aside>;
  return <><button onClick={() => setOpen(true)} className="fixed left-4 top-4 z-30 rounded-xl border border-border bg-card p-2.5 shadow-sm md:hidden" aria-label="Open menu" data-testid="button-open-menu"><Menu size={20} /></button><div className={`fixed inset-0 z-50 md:hidden ${open ? 'visible' : 'invisible'}`}><button onClick={() => setOpen(false)} className={`absolute inset-0 bg-foreground/30 transition-opacity ${open ? 'opacity-100' : 'opacity-0'}`} aria-label="Close navigation overlay" /><div className={`relative h-full w-[280px] transition-transform duration-300 ${open ? 'translate-x-0' : '-translate-x-full'}`}>{content}</div></div><div className="fixed inset-y-0 left-0 z-20 hidden md:block">{content}</div></>;
}

export function AppTopbar({ role = 'customer', title }: { role?: 'customer' | 'technician'; title: string }) {
  return <header className="sticky top-0 z-10 flex h-[76px] items-center justify-between border-b border-border/70 bg-background/85 px-5 backdrop-blur-xl md:px-10"><div className="pl-12 md:pl-0"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-muted-foreground">KaamKhojo / {role === 'technician' ? 'Technician desk' : 'My home'}</p><h1 className="mt-0.5 font-display text-xl font-bold">{title}</h1></div><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-full bg-accent/60 px-3 py-2 text-xs font-bold text-accent-foreground sm:flex"><span className="animate-pulse-dot h-2 w-2 rounded-full bg-teal-600" /> {role === 'technician' ? 'You are available' : 'Bengaluru, 560038'}</div><button className="relative rounded-xl p-2.5 text-muted-foreground hover:bg-muted" aria-label="Notifications"><Bell size={19} /><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-primary" /></button><Link href="/profile" className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary font-display font-bold text-primary-foreground">{role === 'technician' ? 'RK' : 'AM'}</Link></div></header>;
}

export function MobileBottomNav({ role = 'customer' }: { role?: 'customer' | 'technician' }) {
  const [location] = useLocation();
  const items = role === 'technician' ? [{ label: 'Home', href: '/technician-dashboard', icon: Home }, { label: 'Jobs', href: '/technician-dashboard#jobs', icon: CalendarDays }, { label: 'Earnings', href: '/technician-dashboard#earnings', icon: BriefcaseBusiness }, { label: 'Profile', href: '/profile', icon: UserRound }] : [{ label: 'Home', href: '/customer-dashboard', icon: Home }, { label: 'Find', href: '/customer-dashboard#find', icon: Search }, { label: 'Requests', href: '/work-requests', icon: FileText }, { label: 'Profile', href: '/profile', icon: UserRound }];
  return <nav className="fixed inset-x-0 bottom-0 z-30 border-t border-border/80 bg-background/95 px-3 pb-[max(0.75rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur-xl md:hidden"><div className="mx-auto grid max-w-md grid-cols-4 gap-1">{items.map(({ label, href, icon: Icon }) => { const active = location === href || (href.includes('#') && location === href.split('#')[0]); return <Link key={href} href={href} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-bold ${active ? 'bg-primary/15 text-[#96670b]' : 'text-muted-foreground hover:bg-muted'}`}><Icon size={18} />{label}</Link>; })}</div></nav>;
}

export function Shell({ children, role = 'customer', title }: { children: ReactNode; role?: 'customer' | 'technician'; title: string }) {
  return <div className="min-h-[100dvh] bg-background"><AppSidebar role={role} /><div className="md:pl-[260px]"><AppTopbar role={role} title={title} /><main className="mx-auto max-w-[1480px] px-5 pb-24 pt-7 md:px-10 md:py-9">{children}</main></div><MobileBottomNav role={role} /></div>;
}

export function PageIntro({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) {
  return <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.18em] text-primary">{eyebrow}</p><h2 className="font-display text-3xl font-bold tracking-tight md:text-4xl">{title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p></div>{action}</div>;
}

export function Skeleton({ className = '' }: { className?: string }) { return <div className={`animate-pulse rounded-xl bg-muted ${className}`} />; }
export function QueryState({ loading, error, empty, onRetry, children }: { loading: boolean; error: boolean; empty?: boolean; onRetry: () => void; children: ReactNode }) {
  if (loading) return <div className="grid gap-4 md:grid-cols-3"><Skeleton className="h-40" /><Skeleton className="h-40" /><Skeleton className="h-40" /></div>;
  if (error) return <div className="rounded-2xl border border-destructive/20 bg-destructive/5 p-8 text-center"><CircleHelp className="mx-auto mb-3 text-destructive" size={26} /><h3 className="font-display text-xl font-bold">That didn’t load</h3><p className="mt-1 text-sm text-muted-foreground">Please try again. Your place in the app is safe.</p><button onClick={onRetry} className="mt-5 rounded-xl bg-secondary px-4 py-2.5 text-sm font-bold text-secondary-foreground">Try again</button></div>;
  if (empty) return <div className="rounded-2xl border border-dashed border-border bg-card p-10 text-center"><Sparkles className="mx-auto mb-3 text-primary" size={26} /><h3 className="font-display text-xl font-bold">Nothing here yet</h3><p className="mt-1 text-sm text-muted-foreground">The right local expert will show up here soon.</p></div>;
  return <>{children}</>;
}
export function StatCard({ label, value, detail, icon: Icon, tone = 'yellow' }: { label: string; value: string | number; detail: string; icon: typeof Zap; tone?: 'yellow' | 'teal' | 'ink' | 'coral' }) { const colors = { yellow: 'bg-primary/15 text-primary-foreground', teal: 'bg-accent text-accent-foreground', ink: 'bg-secondary text-secondary-foreground', coral: 'bg-[#f5d8d2] text-[#9b4036]' }; return <div className="rounded-2xl border border-card-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${colors[tone]}`}><Icon size={18} /></span><span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">This month</span></div><p className="mt-5 font-display text-3xl font-bold">{value}</p><p className="mt-1 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div>; }
export function StatusBadge({ status }: { status: string }) { const key = status.toLowerCase(); const style = key.includes('complete') ? 'bg-accent text-accent-foreground' : key.includes('confirm') || key.includes('accept') ? 'bg-primary/25 text-[#79510b]' : key.includes('pending') ? 'bg-muted text-muted-foreground' : 'bg-[#f5d8d2] text-[#9b4036]'; return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-bold capitalize ${style}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>; }

export function CategoryCard({ category, onSelect, compact = false }: { category: Category; onSelect: () => void; compact?: boolean }) {
  const Icon = getCategoryIcon(category.icon);
  return <button onClick={onSelect} className={`group rounded-2xl border border-card-border bg-card text-left shadow-sm transition-all hover:-translate-y-1 hover:border-primary/50 hover:shadow-md ${compact ? 'p-3' : 'p-4'}`} data-testid={`button-category-${category.id}`}><span className={`flex items-center justify-center rounded-xl bg-primary/15 text-[#96670b] transition-transform group-hover:rotate-6 ${compact ? 'h-10 w-10' : 'h-11 w-11'}`}><Icon size={compact ? 18 : 20} /></span><p className="mt-3 font-bold">{category.name}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{category.description}</p>{!compact && <p className="mt-3 text-xs font-bold text-[#96670b]">From ₹{category.startingPrice}</p>}</button>;
}
export const CategoryTile = CategoryCard;
export function CategorySection({ title, categories, onSelect }: { title: string; categories: Category[]; onSelect: (category: Category) => void }) { return <section><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Browse by need</p><h2 className="mt-1 font-display text-2xl font-bold">{title}</h2></div><span className="text-xs font-semibold text-muted-foreground">{categories.length} services</span></div><div className="grid grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-5">{categories.map((category) => <CategoryCard key={category.id} category={category} onSelect={() => onSelect(category)} />)}</div></section>; }

export function TechnicianCard({ technician, categories = [], onSave, onView }: { technician: MarketplaceTechnician & { experience?: number; shortDescription?: string }; categories?: Category[]; onSave?: (id: string) => void; onView?: (id: string) => void }) {
  const categoryNames = technician.serviceCategories.map((id) => categories.find((category) => category.id === id)?.name || id).slice(0, 3);
  return <article className="group rounded-2xl border border-card-border bg-card p-4 shadow-sm transition-all hover:-translate-y-1 hover:shadow-md" data-testid={`card-technician-${technician.id}`}><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-secondary font-display font-bold text-secondary-foreground">{technician.avatar || technician.name.slice(0, 2)}</div><div><h3 className="font-bold">{technician.name}</h3><p className="text-xs text-muted-foreground">{technician.specialty}</p></div></div>{onSave && <button onClick={() => onSave(technician.id)} className="rounded-lg p-2 text-muted-foreground hover:bg-[#f5d8d2] hover:text-[#9b4036]" aria-label={`Save ${technician.name}`}><Heart size={17} /></button>}</div><div className="mt-4 flex items-center gap-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1 font-bold text-foreground"><Star size={14} fill="currentColor" className="text-primary" /> {technician.rating}</span><span>({technician.reviewCount} reviews)</span><span className="ml-auto inline-flex items-center gap-1"><MapPin size={13} /> {technician.distance}</span></div><div className="mt-3 flex flex-wrap gap-1.5">{categoryNames.map((name) => <span key={name} className="rounded-full bg-muted px-2 py-1 text-[10px] font-semibold text-muted-foreground">{name}</span>)}</div><p className="mt-3 text-xs leading-5 text-muted-foreground">{technician.shortDescription || 'Trusted local service professional.'}</p><div className="mt-4 flex items-center justify-between border-t border-border pt-3"><span className="inline-flex items-center gap-1.5 text-xs font-semibold text-muted-foreground"><span className={`h-1.5 w-1.5 rounded-full ${technician.availableToday ? 'bg-teal-600' : 'bg-muted-foreground'}`} />{technician.availableToday ? 'Available now' : 'Next slot tomorrow'}</span><button onClick={() => onView?.(technician.id)} className="inline-flex items-center gap-1 text-xs font-bold text-foreground hover:text-[#9b6b0a]" data-testid={`button-view-technician-${technician.id}`}>View profile <ArrowRight size={13} /></button></div></article>;
}

export function SearchBar({ value, onChange, onSubmit, placeholder = 'Search services or technicians' }: { value: string; onChange: (value: string) => void; onSubmit?: () => void; placeholder?: string }) { return <div className="flex max-w-2xl items-center gap-2 rounded-2xl border border-border bg-card p-2 shadow-sm focus-within:border-primary focus-within:ring-4 focus-within:ring-primary/10"><Search className="ml-3 text-muted-foreground" size={19} /><input value={value} onChange={(e) => onChange(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && onSubmit?.()} placeholder={placeholder} className="min-w-0 flex-1 bg-transparent px-2 py-2.5 text-sm font-medium outline-none placeholder:text-muted-foreground/70" data-testid="input-service-search" />{onSubmit && <button onClick={onSubmit} className="rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground" data-testid="button-search-services">Search</button>}</div>; }
export const SearchField = SearchBar;
export function FilterBar({ value, onChange, categories, category, onCategoryChange }: { value: string; onChange: (value: string) => void; categories?: Category[]; category?: string; onCategoryChange?: (value: string) => void }) { const options = ['all', 'available', 'rated', 'nearest', 'experienced']; const labels: Record<string, string> = { all: 'All', available: 'Available Now', rated: 'Top Rated', nearest: 'Nearest', experienced: 'Most Experienced' }; return <div className="space-y-3"><div className="flex flex-wrap gap-2">{options.map((option) => <button key={option} onClick={() => onChange(option)} className={`rounded-full px-3.5 py-2 text-xs font-bold transition-colors ${value === option ? 'bg-secondary text-secondary-foreground' : 'border border-border bg-card text-muted-foreground hover:text-foreground'}`} data-testid={`button-filter-${option}`}>{labels[option]}</button>)}</div>{categories && onCategoryChange && <div className="flex items-center gap-2 overflow-x-auto pb-1"><SlidersHorizontal size={15} className="shrink-0 text-muted-foreground" /><button onClick={() => onCategoryChange('')} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-bold ${!category ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>All services</button>{categories.map((item) => <button key={item.id} onClick={() => onCategoryChange(item.id)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-bold ${category === item.id ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>{item.name}</button>)}</div>}</div>; }
export function ServiceMultiSelect({ categories, selected, onChange }: { categories: Category[]; selected: string[]; onChange: (selected: string[]) => void }) { const toggle = (id: string) => onChange(selected.includes(id) ? selected.filter((item) => item !== id) : [...selected, id]); return <div className="grid gap-2 sm:grid-cols-2">{categories.map((category) => { const Icon = getCategoryIcon(category.icon); const checked = selected.includes(category.id); return <button type="button" key={category.id} onClick={() => toggle(category.id)} className={`flex items-center gap-3 rounded-xl border p-3 text-left transition-colors ${checked ? 'border-primary bg-primary/10' : 'border-border bg-background hover:border-primary/50'}`}><span className={`flex h-9 w-9 items-center justify-center rounded-lg ${checked ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}><Icon size={17} /></span><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{category.name}</span><span className="block truncate text-[11px] text-muted-foreground">{category.description}</span></span><span className={`flex h-5 w-5 items-center justify-center rounded-md border ${checked ? 'border-primary bg-primary text-primary-foreground' : 'border-input'}`}>{checked && <Check size={13} />}</span></button>; })}</div>; }
export function RequestRow({ request, compact = false }: { request: Request; compact?: boolean }) { return <div className={`flex flex-col gap-3 ${compact ? 'py-3' : 'rounded-2xl border border-card-border bg-card p-4 shadow-sm sm:flex-row sm:items-center sm:justify-between'}`}><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-muted text-muted-foreground"><Wrench size={17} /></div><div><p className="text-sm font-bold">{request.service}</p><p className="mt-0.5 text-xs text-muted-foreground">{request.technicianName} <span className="mx-1">•</span> {request.schedule}</p></div></div><div className="flex items-center justify-between gap-5 pl-[52px] sm:pl-0"><span className="font-display font-bold">₹{request.amount.toLocaleString('en-IN')}</span><StatusBadge status={request.status} /></div></div>; }
export function ToastNote({ message, onClose }: { message: string; onClose: () => void }) { return <div className="fixed bottom-5 right-5 z-[60] flex max-w-[calc(100vw-40px)] items-center gap-3 rounded-2xl bg-secondary px-4 py-3 text-sm font-semibold text-secondary-foreground shadow-xl"><Check size={17} className="text-primary" />{message}<button onClick={onClose} className="ml-2 rounded-lg p-1 hover:bg-secondary-foreground/10" aria-label="Close message"><X size={15} /></button></div>; }
